### ISSUE TITLE
Licence problem

### ISSUE THREAD

**Issue by JaniKallankari** [estan/tsp#3]
There seems to be contradictory about the licence. In pypip.org page work is marked as MIT (https://pypi.org/project/fast-tsp/). Here in github code is marked as proprietary license even there is MIT-code included. Could you clarify what is actually used license?

**Comment by estan** [comment]
@JaniKallankari I think you are confusing projects. This project is a TSP solution me and a school mate wrote 10+ years ago. It is licensed MIT as stated in the LICENSE file. Where did you get the impression it is proprietary?

The fast-tsp project on PyPI that you linked seems to be a completely different thing (it is not mine).

**Comment by estan** [comment]
I can see now that the fast-tsp project copied one function from our project here (https://github.com/shmulvad/fast-tsp/blob/main/src/tsp.h#L198-L212).

As you can see, they made a general comment about that, but I guess they should have really included the MIT copyright and permission notice for that section to be compliant with the license. Not a big deal for me, but perhaps @shmulvad can fix?

(fast-tsp seems to be 3-clause BSD, so there is no problem with license compatibility, as long as the copyright and permission notice is included somewhere)

**Comment by shmulvad** [comment]
@estan Thanks for letting me know and apologies about the licensing issue. I have created that as https://github.com/shmulvad/fast-tsp/issues/11 and will fix it within the next week's time.

For the original issue pointed out by @JaniKallankari, it has now been created as https://github.com/shmulvad/fast-tsp/issues/12.

I think the issue on this repo that we are discussing here can be closed as it is not really relevant to `estan/tsp`, but thanks to both of you for bringing the two license issues to my attention.

**Comment by estan** [comment]
@shmulvad Thanks! No hurry
